<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OutreachActivitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'village_id' => 5108050010,
                'ppl_nip' => 197001011990031001,
                'title' => 'Pertemuan Masyarakat Desa Sambangan',
                'location' => json_encode([-8.1501923615788, 115.10028998387088]),
                'address' => 'Jl. Raya Pertanian No.1, Sambangan, Kec. Sukasada, Kab. Buleleng',
                'photo' => json_encode(['/assets/images/gapoktan/gapoktan-1.jpg', '/assets/images/gapoktan/gapoktan-2.jpg', '/assets/images/gapoktan/gapoktan-3.jpg']),
                'file' => '/assets/files/outreach/report-1.pdf',
                'notes' => 'Pertemuan ini membahas tentang peningkatan infrastruktur irigasi.',
                'activity_report' => 'Hasil pertemuan akan disampaikan ke pemerintah setempat.',
                'others_involved' => null,
                'created_at' => '2024-08-16 09:00:00',
                'updated_at' => '2024-08-16 09:00:00',
            ],
            [
                'id' => 2,
                'village_id' => 5108050010,
                'ppl_nip' => 197001011990031001,
                'title' => 'Pelatihan Pertanian Organik',
                'location' => json_encode([-8.15750846905577, 115.1020437383925]),
                'address' => 'Jl. Raya Pertanian No.2, Sambangan, Kec. Sukasada, Kab. Buleleng',
                'photo' => json_encode(['/assets/images/gapoktan/gapoktan-1.jpg', '/assets/images/gapoktan/gapoktan-2.jpg', '/assets/images/gapoktan/gapoktan-3.jpg']),
                'file' => '/assets/files/outreach/report-2.pdf',
                'notes' => 'Pelatihan ini dihadiri oleh petani dari Desa Panji.',
                'activity_report' => 'Petani yang mengikuti pelatihan mengapresiasi metode baru ini.',
                'others_involved' => null,
                'created_at' => '2024-08-16 09:00:00',
                'updated_at' => '2024-08-16 09:00:00',
            ],
            [
                'id' => 3,
                'village_id' => 5108050010,
                'ppl_nip' => 197001011990031001,
                'title' => 'Kunjungan Lapangan ke Lahan Budidaya Hortikultura',
                'location' => json_encode([-8.150564370273274, 115.09603086574704]),
                'address' => 'Jl. Raya Pertanian No.3, Sambangan, Kec. Sukasada, Kab. Buleleng',
                'photo' => json_encode(['/assets/images/gapoktan/gapoktan-1.jpg', '/assets/images/gapoktan/gapoktan-2.jpg', '/assets/images/gapoktan/gapoktan-3.jpg']),
                'file' => '/assets/files/outreach/report-3.pdf',
                'notes' => 'Kunjungan ini bertujuan untuk mempelajari sistem irigasi yang digunakan.',
                'activity_report' => 'Hasil kunjungan ini akan dijadikan referensi bagi petani lokal.',
                'others_involved' => null,
                'created_at' => '2024-08-17 10:00:00',
                'updated_at' => '2024-08-17 10:00:00',
            ],
            [
                'id' => 4,
                'village_id' => 5108050010,
                'ppl_nip' => 197001011990031001,
                'title' => 'Pelatihan Pemeliharaan Tanaman Kopi',
                'location' => json_encode([-8.1762321339242, 115.10705446559706]),
                'address' => 'Jl. Raya Pertanian No.4, Sambangan, Kec. Sukasada, Kab. Buleleng',
                'photo' => json_encode(['/assets/images/gapoktan/gapoktan-1.jpg', '/assets/images/gapoktan/gapoktan-2.jpg', '/assets/images/gapoktan/gapoktan-3.jpg']),
                'file' => '/assets/files/outreach/report-4.pdf',
                'notes' => 'Pelatihan ini difokuskan pada teknik pemupukan yang efektif.',
                'activity_report' => 'Petani kopi merespon positif terhadap teknik baru ini.',
                'others_involved' => null,
                'created_at' => '2024-08-17 10:00:00',
                'updated_at' => '2024-08-17 10:00:00',
            ],
            [
                'id' => 5,
                'village_id' => 5108050010,
                'ppl_nip' => 197502051995032001,
                'title' => 'Diskusi Lingkungan Hidup Desa Sambangan',
                'location' => json_encode([-8.191855181906336, 115.10943456118594]),
                'address' => 'Jl. Raya Pertanian No.5, Sambangan, Kec. Sukasada, Kab. Buleleng',
                'photo' => json_encode(['/assets/images/gapoktan/gapoktan-1.jpg', '/assets/images/gapoktan/gapoktan-2.jpg', '/assets/images/gapoktan/gapoktan-3.jpg']),
                'file' => '/assets/files/outreach/report-5.pdf',
                'notes' => 'Diskusi ini mengangkat isu pengelolaan limbah pertanian secara berkelanjutan.',
                'activity_report' => 'Pemerintah setempat akan mengambil langkah-langkah konkret setelah diskusi ini.',
                'others_involved' => null,
                'created_at' => '2024-08-18 09:00:00',
                'updated_at' => '2024-08-18 09:00:00',
            ],
            [
                'id' => 6,
                'village_id' => 5108050010,
                'ppl_nip' => 197502051995032001,
                'title' => 'Pelatihan Penggunaan Teknologi Irigasi Modern',
                'location' => json_encode([-8.1501923615788, 115.10028998387088]),
                'address' => 'Jl. Raya Pertanian No.1, Sambangan, Kec. Sukasada, Kab. Buleleng',
                'photo' => json_encode(['/assets/images/gapoktan/gapoktan-1.jpg', '/assets/images/gapoktan/gapoktan-2.jpg', '/assets/images/gapoktan/gapoktan-3.jpg']),
                'file' => '/assets/files/outreach/report-6.pdf',
                'notes' => 'Pelatihan ini menitikberatkan pada efisiensi penggunaan air.',
                'activity_report' => 'Peserta pelatihan merasa terbantu dengan teknologi baru ini.',
                'others_involved' => null,
                'created_at' => '2024-08-18 09:00:00',
                'updated_at' => '2024-08-18 09:00:00',
            ],
            [
                'id' => 7,
                'village_id' => 5108050010,
                'ppl_nip' => 197502051995032001,
                'title' => 'Kampanye Penanaman Pohon',
                'location' => json_encode([-8.15750846905577, 115.1020437383925]),
                'address' => 'Jl. Raya Pertanian No.2, Sambangan, Kec. Sukasada, Kab. Buleleng',
                'photo' => json_encode(['/assets/images/gapoktan/gapoktan-1.jpg', '/assets/images/gapoktan/gapoktan-2.jpg', '/assets/images/gapoktan/gapoktan-3.jpg']),
                'file' => '/assets/files/outreach/report-7.pdf',
                'notes' => 'Kampanye ini bertujuan untuk meningkatkan kesadaran lingkungan.',
                'activity_report' => 'Sejumlah pohon berhasil ditanam di sekitar lahan pertanian.',
                'others_involved' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'village_id' => 5108050010,
                'ppl_nip' => 197502051995032001,
                'title' => 'Pelatihan Pemanfaatan Pupuk Organik',
                'location' => json_encode([-8.150564370273274, 115.09603086574704]),
                'address' => 'Jl. Raya Pertanian No.3, Sambangan, Kec. Sukasada, Kab. Buleleng',
                'photo' => json_encode(['/assets/images/gapoktan/gapoktan-1.jpg', '/assets/images/gapoktan/gapoktan-2.jpg', '/assets/images/gapoktan/gapoktan-3.jpg']),
                'file' => '/assets/files/outreach/report-8.pdf',
                'notes' => 'Pelatihan ini memberikan panduan praktis dalam pembuatan pupuk organik.',
                'activity_report' => 'Petani merespon positif dan mulai menerapkan teknik baru ini di lahan mereka.',
                'others_involved' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'village_id' => 5108050010,
                'ppl_nip' => 197502051995032001,
                'title' => 'Diskusi Penyuluhan Pertanian Berkelanjutan',
                'location' => json_encode([-8.1762321339242, 115.10705446559706]),
                'address' => 'Jl. Raya Pertanian No.4, Sambangan, Kec. Sukasada, Kab. Buleleng',
                'photo' => json_encode(['/assets/images/gapoktan/gapoktan-1.jpg', '/assets/images/gapoktan/gapoktan-2.jpg', '/assets/images/gapoktan/gapoktan-3.jpg']),
                'file' => '/assets/files/outreach/report-9.pdf',
                'notes' => 'Diskusi ini membahas tentang teknik tanam yang ramah lingkungan.',
                'activity_report' => 'Petani mengapresiasi informasi yang didapatkan dari diskusi ini.',
                'others_involved' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'village_id' => 5108050010,
                'ppl_nip' => 197502051995032001,
                'title' => 'Pelatihan Pemeliharaan Tanaman Hortikultura',
                'location' => json_encode([-8.191855181906336, 115.10943456118594]),
                'address' => 'Jl. Raya Pertanian No.5, Sambangan, Kec. Sukasada, Kab. Buleleng',
                'photo' => json_encode(['/assets/images/gapoktan/gapoktan-1.jpg', '/assets/images/gapoktan/gapoktan-2.jpg', '/assets/images/gapoktan/gapoktan-3.jpg']),
                'file' => '/assets/files/outreach/report-10.pdf',
                'notes' => 'Pelatihan ini memberikan teknik dalam pemangkasan tanaman hortikultura.',
                'activity_report' => 'Hasil pelatihan ini berhasil meningkatkan kualitas hasil panen.',
                'others_involved' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert data into the outreach_activities table
        DB::table('outreach_activities')->insert($data);
    }
}
